# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: sonicbld
jobs:
- job:
  steps:
  - checkout: self
    persistCredentials: true
  - task: TriggerBuild@4
    inputs:
      definitionIsInCurrentTeamProject: false
      tfsServer: 'https://dev.azure.com/msazure/'
      teamProject: 'b32aa71e-8ed2-41b2-9d77-5bc261222004'
      buildDefinition: '329541'
      queueBuildForUserThatTriggeredBuild: false
      ignoreSslCertificateErrors: true
      useSameSourceVersion: false
      useCustomSourceVersion: false
      useSameBranch: false
      branchToUse: 'test'
      waitForQueuedBuildsToFinish: true
      waitForQueuedBuildsToFinishRefreshTime: '60'
      failTaskIfBuildsNotSuccessful: true
      cancelBuildsIfAnyFails: false
      treatPartiallySucceededBuildAsSuccessful: false
      downloadBuildArtifacts: false
      storeInEnvironmentVariable: false
      templateParameters: 'prid: $(System.PullRequest.PullRequestNumber)'
      authenticationMethod: 'Personal Access Token'
      password: '$(System.AccessToken)'
      enableBuildInQueueCondition: false
      dependentOnSuccessfulBuildCondition: false
      dependentOnFailedBuildCondition: false
      checkbuildsoncurrentbranch: false
      failTaskIfConditionsAreNotFulfilled: false
