# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - 202012
  paths:
    exclude:
      - .github

pr:
  branches:
    include:
      - master
      - 202012
      - bullseye
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: sonic-mgmt
    type: github
    name: Azure/sonic-mgmt
    endpoint: build
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage
    endpoint: build
    ref: master

variables:
- template: .azure-pipelines/azure-pipelines-repd-build-variables.yml
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: .azure-pipelines/template-variables.yml
- ${{ else }}:
  - template: .azure-pipelines/template-variables.yml@buildimage
- name: CACHE_MODE
  value: rcache 

stages:
- stage: BuildVS
  pool: sonicbld
  jobs:
  - job: one
    steps:
    - checkout: self
      submodules: recursive
      clean: true
    - script: |
        git submodule
        cd src/sonic-swss-common
        git remote -v
