# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: BuildVS
  pool: sonicbld
  jobs:
  - job: one
    steps:
    - checkout: self
      submodules: recursive
      clean: true
    - script: |
        git submodule
        cd src/sonic-swss-common
        git remote -v
