# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: sonicbld
jobs:
- job:
  steps:
  - checkout: none
  - task: TriggerBuild@4
    inputs:
      definitionIsInCurrentTeamProject: false
      tfsServer: 'https://dev.azure.com/msazure/'
      teamProject: 'One'
      buildDefinition: '329541'
      queueBuildForUserThatTriggeredBuild: true
      ignoreSslCertificateErrors: true
      branchToUse: 'internal'
      waitForQueuedBuildsToFinish: true
      waitForQueuedBuildsToFinishRefreshTime: '60'
      failTaskIfBuildsNotSuccessful: true
      templateParameters: 'branch: $(System.PullRequest.PullRequestId)'
      authenticationMethod: 'Personal Access Token'
      password: '$(PAT)'
