# sonic broadcom one image installer                                                                                         

SONIC_ONE_NBI_IMAGE = sonic-nbi-broadcom.bin
$(SONIC_ONE_NBI_IMAGE)_MACHINE = broadcom
$(SONIC_ONE_NBI_IMAGE)_IMAGE_TYPE = nbi
$(SONIC_ONE_NBI_IMAGE)_LAZY_INSTALLS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_N3132_PLATFORM_MODULE) 
$(SONIC_ONE_NBI_IMAGE)_INSTALLS += $(BRCM_OPENNSL_KERNEL) $(SONIC_CISCO_PLATFORM_API_PY2) $(SONIC_CISCO_PLATFORM_API_PY3) $(CISCO_NBI_PACKAGE) 
$(SONIC_ONE_NBI_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)
$(SONIC_ONE_NBI_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
SONIC_INSTALLERS += $(SONIC_ONE_NBI_IMAGE)

