CISCO_NBI_PACKAGE = cisco-nbi-package_1.0_amd64.deb
$(CISCO_NBI_PACKAGE)_PATH = $(PLATFORM_PATH)
SONIC_COPY_DEBS += $(CISCO_NBI_PACKAGE)
SONIC_STRETCH_DEBS += $(CISCO_NBI_PACKAGE)

# SONIC_PLATFORM_API_PY2 package
SONIC_CISCO_PLATFORM_API_PY2 = python-sonic-platform-cisco_1.0_all.deb
$(SONIC_CISCO_PLATFORM_API_PY2)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cisco/sonic-platform
$(SONIC_CISCO_PLATFORM_API_PY2)_PLATFORM = x86_64-n3164-r0 x86_64-m3000-r0 x86_64-m3000-r1
SONIC_DPKG_DEBS += $(SONIC_CISCO_PLATFORM_API_PY2)
export SONIC_CISCO_PLATFORM_API_PY2

# SONIC_PLATFORM_API_PY3 package
SONIC_CISCO_PLATFORM_API_PY3 = python3-sonic-platform-cisco_1.0_all.deb
$(SONIC_CISCO_PLATFORM_API_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cisco/sonic-platform
$(SONIC_CISCO_PLATFORM_API_PY3)_PLATFORM = x86_64-n3164-r0 x86_64-m3000-r0 x86_64-m3000-r1
$(eval $(call add_extra_package,$(SONIC_CISCO_PLATFORM_API_PY2),$(SONIC_CISCO_PLATFORM_API_PY3)))
export SONIC_CISCO_PLATFORM_API_PY3

