# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - internal

trigger: none
pr: none

stages:
- stage: Build
  pool: sonic-image-builder
  variables:
    - group: SONIC-BUILD-VG-1
    - name: PUBLISH_BLOB_PREFIX
      value: pipelines/$(Build.DefinitionName)/$(Build.SourceBranchName)
    - name: CACHE_MODE
      value: none
    - ${{ if contains(variables['Build.SourceBranchName'], '202012') }}:
      - name: VERSION_CONTROL_OPTIONS
        value: 'SONIC_VERSION_CONTROL_COMPONENTS=deb,py2,py3,web'
  jobs:
  - template: ../.azure-pipelines/azure-pipelines-build.yml
    parameters:
      buildOptions: 'ENABLE_DHCP_GRAPH_SERVICE=y PASSWORD=$SONIC_PASSWORD SHUTDOWN_BGP_ON_START=y ENABLE_PFCWD_ON_START=y SONIC_BUILD_JOBS=$(nproc) ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobFilters: none
      preSteps:
        - script: |
            set -xe
            . functions.sh
            SONIC_VERSION=$(sonic_get_version)
            rm -f rules/config.user || true
            echo "INCLUDE_ACMS = n" >>rules/config.user
            echo "INCLUDE_MUX = n" >>rules/config.user
            echo "INCLUDE_KUBERNETES = n" >>rules/config.user
            echo "INCLUDE_MACSEC = n" >>rules/config.user
          displayName: Get sonic version
      postSteps:
        - script: |
            set -x
            mv target/sonic-$(GROUP_NAME).bin target/sonic-$(GROUP_NAME)-slim-$SONIC_VERSION.bin
            mv target/sonic-aboot-$(GROUP_NAME).swi target/sonic-aboot-$(GROUP_NAME)-slim-$SONIC_VERSION.swi
          displayName: Change artifacts name
        - template: template-upload.yml
      jobGroups:
        - name: broadcom
          variables:
            swi_image: yes

