trigger: none
pr: none

resources:
 pipelines:
   - pipeline: buildimage
     source: Networking-acs-buildimage-Official
     trigger:
      enabled: true
      branches:
       include:
         - '*'

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: sonic-image-builder


variables:
- group: SONIC-BUILD-VG-1
- name: PUBLISH_BLOB_PREFIX
  value: pipelines/Networking-acs-buildimage-Official/$(Build.SourceBranchName)

stages:
- stage: Build
  variables:
    BUILD_TIMESTAMP: $[format('{0:yyyyMMdd}.{0:HHmmss}', pipeline.startTime)]
    BRANCH_NAME: $(Build.SourceBranchName)
    BUILD_NUMBER: $(resources.pipeline.buildimage.runID)
    VERSION_PATH: target/sonic.version
  jobs:
  - job: Build
    steps:
    - task: SSH@0
      displayName: "Make soft links for trusty8"
      inputs:
        sshEndpoint: 'acs-trusty8'
        runOptions: 'inline'
        readyTimeout: '20000'
        inline: |
          echo "Make link for $(PUBLISH_BLOB_PREFIX)"
          for platform in `ls /azmirrors/$(PUBLISH_BLOB_PREFIX)`; do
            latest_path=/azmirrors/$(PUBLISH_BLOB_PREFIX)/$platform/$(BUILD_NUMBER)
            [ ! -d $latest_path ] && continue
            SONIC_VERSION=$(cat $latest_path/target/sonic.version)
            LATEST_TAG=$(cat $latest_path/target/sonic.tag)
            LINK_FOLDERNAMES=.
            [ "$SONIC_VERSION" == "$LATEST_TAG" ] && LINK_FOLDERNAMES=". tagged"
            for link_foldername in $LINK_FOLDERNAMES; do
              LATEST_VERSION=
              PREVIOUS_VERSION=
              link_path=/data/$(dirname $(PUBLISH_BLOB_PREFIX))/$platform/$(BRANCH_NAME)/$link_foldername
              [ -e $link_path/latest ] && LATEST_VERSION=$(cat $link_path/latest/target/sonic.version)
              mkdir -p $link_path

              # Make soft links for latest and prev
              prev_link_path=$(realpath $link_path/latest)
              # If the latest version in the storage account is the same as the current build version, not update the prev link
              if [ -e $prev_link_path ] && [ "$LATEST_VERSION" != "$SONIC_VERSION" ]; then
                [ -L $link_path/prev ] && PREVIOUS_VERSION=$(cat $link_path/prev/target/sonic.version)
                ln -nsf "$prev_link_path" "$link_path/prev"
              fi

              ln -nsf "$latest_path" "$link_path/latest"

              # Make soft links for installers
              installers_path=$link_path/installers
              mkdir -p $installers_path
              ln -sf $latest_path/target/sonic.version $installers_path/sonic.version
              for installer in `cat $latest_path/target/sonic-installers`; do
                image=$(echo $installer | cut -d, -f1)
                version_image=$(echo $installer | cut -d, -f2)
                ln -sf $latest_path/target/$version_image $installers_path/$image
                ln -sf $latest_path/target/$version_image $link_path/$version_image
                ln -sf latest/target/$image $link_path/$image
                ln -sf prev/target/$image $link_path/$image.PREV.1
              done

              # Remove the old soft links
              echo "PREVIOUS_VERSION=$PREVIOUS_VERSION"
              if [ -n "$PREVIOUS_VERSION" ]; then
                rm -f $link_path/*"$PREVIOUS_VERSION"*
              fi
            done
          done
