schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - internal
    - internal-202012
    - internal-201911
    - internal-201811
  always: false
trigger: none
pr: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: sonic-image-builder

parameters:
- name: 'jobFilters'
  type: object
  default:
  - vs
  - broadcom
  - mellanox
  - marvell-armhf
- name: 'trusty8LinkPath'
  type: string
  default: 'default'

variables:
- group: SONIC-BUILD-VG-1
- name: PUBLISH_BLOB_PREFIX
  value: pipelines/$(Build.DefinitionName)/$(Build.SourceBranchName)

stages:
- stage: Build
  variables:
    BUILD_TIMESTAMP: $[format('{0:yyyyMMdd}.{0:HHmmss}', pipeline.startTime)]
    BRANCH_NAME: $(Build.SourceBranchName)
    BUILD_NUMBER: $(Build.BuildId)
    PLATFORM_ARCH: amd64
    PASSWORD: $(SONIC_PASSWORD)
    BUILD_OPTIONS: 'SONIC_BUILD_JOBS=$(nproc) ENABLE_DHCP_GRAPH_SERVICE=y SHUTDOWN_BGP_ON_START=y ENABLE_PFCWD_ON_START=y'
    VERSION_PATH: target/sonic.version
    DOCKER_DATA_ROOT_FOR_MULTIARCCH: /data/march/docker
  jobs:
  - template: ../.azure-pipelines/azure-pipelines-job-groups.yml
    parameters:
      scriptEnv:
        PASSWORD: '$(PASSWORD)'
      jobFilters: ${{ parameters.jobFilters }}
      preSteps:
        - template: ../.azure-pipelines/cleanup.yml
        - checkout: self
          clean: true
          submodules: recursive
          displayName: 'Checkout code'
        - script: |
            git checkout -b $(Build.SourceBranchName)
            . functions.sh
            SONIC_VERSION=$(sonic_get_version)
            echo SONIC_VERSION=${SONIC_VERSION} > sonic.properties
            LATEST_TAG=$(git tag --points-at HEAD | grep -v -e '.*-merge' | head -n 1)
            mkdir -p target/release
            rm -f target/sonic-installers
            echo $SONIC_VERSION > $VERSION_PATH
            echo $LATEST_TAG > target/sonic.tag 
            echo "SONIC_VERSION=$SONIC_VERSION, LATEST_TAG=$LATEST_TAG"
            echo "##vso[task.setvariable variable=SONIC_VERSION]$SONIC_VERSION"
            echo "##vso[task.setvariable variable=LATEST_TAG]$LATEST_TAG"
            ENABLE_DOCKER_BASE_PULL=y make PLATFORM=$(GROUP_NAME) PLATFORM_ARCH=$(PLATFORM_ARCH) $(BUILD_OPTIONS) configure
          displayName: 'Make configure'
      postSteps:
        - publish: $(System.DefaultWorkingDirectory)/target
          artifact: 'sonic-buildimage.$(GROUP_NAME)'
          displayName: "Archive sonic image"
        - script: |
            for image in `ls target | grep -E "\.(swi|bin|raw|deb)$"`; do
              version_image=$(echo $image | sed -E "s/(-dbg\.\w+|\.\w+)$/-$(SONIC_VERSION)\1/")
              echo "$image,$version_image" >> target/sonic-installers 
              cp -f target/$image target/$version_image
            done
          displayName: "Copy installers"
        - script: |
            mkdir -p azcopy
            pushd azcopy
            wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
            popd
            export AZCOPY_LOG_LOCATION=$(pwd)/azcopy
            PUBLISH_PLATFORM_URL="https://$(SONIC_STORAGE_ACCOUNT).blob.core.windows.net/images/$(PUBLISH_BLOB_PREFIX)/$(GROUP_NAME)"
            PUBLISH_URL="$PUBLISH_PLATFORM_URL/$(Build.BuildId)$StorageSASKey"
            azcopy/azcopy copy target "$PUBLISH_PLATFORM_URL/$(Build.BuildId)$StorageSASKey" --recursive=true --put-md5
            touch prev_build
            azcopy/azcopy copy "$PUBLISH_PLATFORM_URL/latest_build$StorageSASKey" latest_build || true
            [ -f latest_build ] && mv latest_build prev_build
            echo $(Build.BuildId) > latest_build
            azcopy/azcopy copy latest_build "$PUBLISH_PLATFORM_URL/latest_build$StorageSASKey"  --put-md5
            azcopy/azcopy copy prev_build "$PUBLISH_PLATFORM_URL/prev_build$StorageSASKey"  --put-md5
          env:
            StorageSASKey: $(SONIC_STORAGE_SASKEY)
          condition: not(startsWith(variables['PLATFORM_ARCH'], 'armhf'))
          displayName: "Publish to Azure Storage by azcopy"
        - script: |
            # currently the azcopy is not supported in arm, see https://github.com/Azure/azure-storage-azcopy/issues/882
            [ ! -e /agent/blobfuse ] && mkdir -p /agent/blobfuse /agent/blobfuse-cache
            sudo umount /agent/blobfuse > /dev/null 2>&1
            if ! mountpoint -q  /agent/blobfuse; then
              blobfuse /agent/blobfuse --tmp-path=/agent/blobfuse-cache --container-name=images
            fi
            PUBLISH_PATH=/agent/blobfuse/$(PUBLISH_BLOB_PREFIX)/$(GROUP_NAME)
            mkdir -p $PUBLISH_PATH/$(Build.BuildId)
            cp -rf target $PUBLISH_PATH/$(Build.BuildId)/
            touch prev_build
            [ -f $PUBLISH_PATH/latest_build ] && cp $PUBLISH_PATH/latest_build prev_build
            echo $(Build.BuildId) > latest_build
            cp latest_build $PUBLISH_PATH/
            cp prev_build $PUBLISH_PATH/
          condition: startsWith(variables['PLATFORM_ARCH'], 'armhf')
          env:
            AZURE_STORAGE_ACCOUNT: $(SONIC_STORAGE_ACCOUNT)
            AZURE_STORAGE_SAS_TOKEN: $(SONIC_STORAGE_SASKEY)
          displayName: "Publish to Azure Storage by blobfuse"
        - task: SSH@0
          displayName: "Make soft links for trusty8"
          inputs:
            sshEndpoint: 'acs-trusty8'
            runOptions: 'inline'
            readyTimeout: '20000'
            inline: |
              echo "Make link for $(PUBLISH_BLOB_PREFIX)"
              LINK_FOLDERNAMES=.
              [ "$(SONIC_VERSION)" == "$(LATEST_TAG)" ] && LINK_FOLDERNAMES=". tagged"
              for link_foldername in $LINK_FOLDERNAMES; do
                LATEST_VERSION=
                PREVIOUS_VERSION=
                latest_path=/azmirrors/$(PUBLISH_BLOB_PREFIX)/$(GROUP_NAME)/$(BUILD_NUMBER)
                [[ "${{ parameters.trusty8LinkPath }}" != 'default' ]] && BRANCH_NAME=${{ parameters.trusty8LinkPath }}
                link_path=/data/$(dirname $(PUBLISH_BLOB_PREFIX))/$(GROUP_NAME)/$(BRANCH_NAME)/$link_foldername
                [ -e $link_path/latest ] && LATEST_VERSION=$(cat $link_path/latest/target/sonic.version)
                mkdir -p $link_path

                # Make soft links for latest and prev
                prev_link_path=$(realpath $link_path/latest)
                # If the latest version in the storage account is the same as the current build version, not update the prev link
                if [ -e $prev_link_path ] && [ "$LATEST_VERSION" != "$(SONIC_VERSION)" ]; then
                  [ -L $link_path/prev ] && PREVIOUS_VERSION=$(cat $link_path/prev/target/sonic.version)
                  ln -nsf "$prev_link_path" "$link_path/prev"
                fi

                ln -nsf "$latest_path" "$link_path/latest"

                # Make soft links for installers
                installers_path=$link_path/installers
                mkdir -p $installers_path
                ln -sf $latest_path/target/sonic.version $installers_path/sonic.version
                for installer in `cat $latest_path/target/sonic-installers`; do
                  image=$(echo $installer | cut -d, -f1)
                  version_image=$(echo $installer | cut -d, -f2)
                  ln -sf $latest_path/target/$version_image $installers_path/$image
                  ln -sf $latest_path/target/$version_image $link_path/$version_image
                  ln -sf latest/target/$image $link_path/$image
                  ln -sf prev/target/$image $link_path/$image.PREV.1
                done

                # Remove the old soft links
                echo "PREVIOUS_VERSION=$PREVIOUS_VERSION"
                if [ -n "$PREVIOUS_VERSION" ]; then
                  rm -f $link_path/*"$PREVIOUS_VERSION"*
                fi
              done
        - script: |
            SONIC_VERSION=$(cat $VERSION_PATH)
            PORT=443
            DOCKERS=$(ls target/docker-*.gz)
            BRANCH=$(Build.SourceBranchName)
            for f in $DOCKERS; do
              echo $f
              ./push_docker.sh $f $REGISTRY_SERVER $PORT $REGISTRY_USERNAME "$REGISTRY_PASSWD" $SONIC_VERSION $BRANCH
              ./push_docker.sh $f $REGISTRY_SERVER $PORT $REGISTRY_USERNAME "$REGISTRY_PASSWD" latest $BRANCH
            done
          env:
            REGISTRY_PASSWD: $(REGISTRY_PASSWD)
            ACS_REGISTRY_PASSWD: $(ACS_REGISTRY_PASSWD)
            BUILD_NUMBER: $(Build.BuildId)
          displayName: "Publish to Docker Registry"
        - task: ComponentGovernanceComponentDetection@0
          condition: not(startsWith(variables['PLATFORM_ARCH'], 'armhf'))
        - script: |
            sudo rm -rf fsroot
            docker rmi -f $(docker images docker-* -a -q | grep docker-) || true
          displayName: "CleanUp"
      jobGroups:
        - name: vs
          script: |
            make target/sonic-vs.bin target/sonic-vs.img.gz
        - name: broadcom
          script: |
            set -ex
            OPTIONS="$BUILD_OPTIONS PASSWORD=$PASSWORD"

            echo "==== Building slim images"
            echo "INCLUDE_ACMS = n" > rules/config.user
            echo "INCLUDE_MUX = n" >> rules/config.user
            echo "INCLUDE_KUBERNETES = n" >> rules/config.user
            make $OPTIONS target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi
            mv target/sonic-broadcom.bin target/sonic-broadcom-slim.bin
            mv target/sonic-aboot-broadcom.swi target/sonic-aboot-broadcom-slim.swi
            rm rules/config.user
            echo "==== Finished building slim images"

            echo "==== Building regular images"
            make $OPTIONS target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi target/sonic-broadcom.raw
            mv target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi target/sonic-broadcom.raw target/release/
            make $OPTIONS target/debs/buster/python-saithrift_0.9.4_amd64.deb
            cp target/debs/buster/python-saithrift_0.9.4_amd64.deb target/
            echo "==== Finished building regular images"

            echo "==== Building syncd-rpc docker"
            make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-brcm-rpc.gz
            echo "==== Finished building syncd-rpc docker"

            echo "==== Building saiserver docker"
            make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-saiserver-brcm.gz
            echo "==== Finished building saiserver docker"

            echo "==== Building one debug image"
            make $OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-broadcom.bin
            mv target/sonic-broadcom.bin target/sonic-broadcom-dbg.bin
            echo "==== Finished building one debug image"

            mv target/release/* target/
        - name: mellanox
          script: |
            OPTIONS="$BUILD_OPTIONS INCLUDE_RESTAPI=y INCLUDE_VNET_MONITOR=y PASSWORD=$PASSWORD"
            make $OPTIONS INCLUDE_NAT=n INCLUDE_RESTAPI=y INCLUDE_VNET_MONITOR=y target/sonic-mellanox.bin
            make $OPTIONS INCLUDE_NAT=n ENABLE_SYNCD_RPC=y INCLUDE_RESTAPI=y INCLUDE_VNET_MONITOR=y target/docker-syncd-mlnx-rpc.gz || true
            mv target/sonic-mellanox.bin target/release/
            cp target/debs/stretch/python-saithrift_0.9.4_amd64.deb target/python-saithrift_0.9.4_amd64.deb

            make $OPTIONS INSTALL_DEBUG_TOOLS=y INCLUDE_RESTAPI=y INCLUDE_VNET_MONITOR=y INCLUDE_NAT=n target/sonic-mellanox.bin
            mv target/sonic-mellanox.bin target/sonic-mellanox-dbg.bin
            mv target/release/* target/
        - name: barefoot
          script: |
            sudo modprobe overlay
            OPTIONS="$BUILD_OPTIONS ENABLE_NAT=n PASSWORD=$PASSWORD"
            make $OPTIONS ENABLE_RESTAPI=y target/docker-syncd-bfn-rpc.gz
            make $OPTIONS target/sonic-aboot-barefoot.swi
        - name: marvell-armhf
          pool:
            name: 'CDPCustom- sonic-build-agents'
            demands:
            - Docker.Arch -equals armhf
          timeoutInMinutes: 4320
          variables:
            PLATFORM_ARCH: armhf
          script: |
            echo "INCLUDE_ACMS = n" > rules/config.user
            OPTIONS="$BUILD_OPTIONS PASSWORD=$PASSWORD"
            make $OPTIONS target/sonic-marvell-armhf.bin
