# Docker image containing Python 2 and some SONiC code

DOCKER_PYTHON2_LAYER_BUSTER_STEM = docker-python2-layer-buster
DOCKER_PYTHON2_LAYER_BUSTER = $(DOCKER_PYTHON2_LAYER_BUSTER_STEM).gz
DOCKER_PYTHON2_LAYER_BUSTER_DBG = $(DOCKER_PYTHON2_LAYER_BUSTER_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PYTHON2_LAYER_BUSTER)_PATH = $(DOCKERS_PATH)/$(DOCKER_PYTHON2_LAYER_BUSTER_STEM)

$(DOCKER_PYTHON2_LAYER_BUSTER)_DEPENDS += $(LIBSWSSCOMMON) $(PYTHON_SWSSCOMMON)

$(DOCKER_PYTHON2_LAYER_BUSTER)_PYTHON_WHEELS += $(SWSSSDK_PY2)
$(DOCKER_PYTHON2_LAYER_BUSTER)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY2)

$(DOCKER_PYTHON2_LAYER_BUSTER)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)
$(DOCKER_PYTHON2_LAYER_BUSTER)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG)

$(DOCKER_PYTHON2_LAYER_BUSTER)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

$(DOCKER_PYTHON2_LAYER_BUSTER)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)

SONIC_DOCKER_IMAGES += $(DOCKER_PYTHON2_LAYER_BUSTER)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PYTHON2_LAYER_BUSTER_DBG)
