#!/bin/bash

INSTALL=
. /usr/local/share/buildinfo/scripts/buildinfo_base.sh

REAL_COMMAND=$APT_REAL_COMMAND
[ -z "$REAL_COMMAND" ] && REAL_COMMAND=$(get_command apt-get)
if [ -z "$REAL_COMMAND" ]; then
    echo "The command apt-get does not exist." 1>&2
    exit 1
fi

INSTALL=$(check_apt_install "$@")
if [ "$INSTALL" == y ]; then
    check_apt_version "$@"
    run_with_retry $REAL_COMMAND "$@"
    command_result=$?
    exit $command_result
else
    if [[ " $@ " == *" purge "* || " $@ " == *" remove "* ]]; then
      # When running the purge command, collect the debian versions
      dpkg-query -W -f '${Package}==${Version}\n' >> $POST_VERSION_PATH/purge-versions-deb
      chmod a+wr $POST_VERSION_PATH/purge-versions-deb
    fi
    run_with_retry $REAL_COMMAND "$@"
fi

