#!/bin/bash

. /usr/local/share/buildinfo/scripts/buildinfo_base.sh

log_file=$BUILD_VERSION_PATH/versions-go.log
[ -d /sonic/target ] && log_file=/sonic/target/versions/default/versions-go.log
REAL_COMMAND=$(get_command go $log_file)
[ -z "$REAL_COMMAND" ] && REAL_COMMAND=/usr/local/go/bin/go

if [[ "$1" == 'get' ]];then
	echo With retry: $REAL_COMMAND $@ >> $log_file
	run_with_retry $REAL_COMMAND "$@"
else
	echo Not  retry: $REAL_COMMAND $@ >> $log_file
	$REAL_COMMAND "$@"
fi
exit
