# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - 202012
  always: true

trigger: none
pr: none

stages:
- stage: Build
  pool: sonicbld
  variables:
    CACHE_MODE: none
    VERSION_CONTROL_OPTIONS: 'SONIC_VERSION_CONTROL_COMPONENTS=deb,py2,py3,web,git,docker'
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: 'DEFAULT_CONTAINER_REGISTRY=publicmirror.azurecr.io USERNAME=admin SONIC_BUILD_JOBS=$(nproc) ${{ variables.VERSION_CONTROL_OPTIONS }}'
      jobFilters: none
