steps:
- script: |
    echo "##vso[task.setvariable variable=SKIP_VSTEST;isOutput=true]NO"
    set -ex
    for i in $(git diff HEAD~ | grep '^diff ' | awk '{print$NF}' | sed 's#b/##')
    do
      # if code is not in /platform, /files/build/versions and .azure-pipelines, don't skip.
      echo $i | grep -v "^platform" | grep -v "^files/build/versions" | grep -v "^.azure-pipelines" && exit 0
      # if code is in /platform/vs, don't skip
      echo $i | grep "^platform/vs" && exit 0
      # if code is in .azure-pipelines/run-test-template.yml, don't skip
      echo $i | grep "^.azure-pipelines/run-test-template.yml" && exit 0
    done
    set +x
    echo "##vso[task.setvariable variable=SKIP_VSTEST;isOutput=true]YES"
  name: SetVar
  displayName: "Set SKIP_VSTST variable"
