name: CherryPick
on:
  pull_request_target:
    types:
    - labeled
    - closed
    branches:
    - master

jobs:
  if_merged:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Test
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo $GITHUB_CONTEXT
        echo The PR is merged.
