name: CherryPick
on:
  pull_request_target:
    types:
    - closed
    branches:
    - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $GITHUB_CONTEXT
        echo The PR is merged.
      GITHUB_CONTEXT: ${{ toJson(github) }}
