name: CherryPick
on:
  pull_request_target:
    types:
    - labeled
    - closed
    branches:
    - master

jobs:
  job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: install dependency
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install -y jq
    - name: Test
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        set -e
        echo $GITHUB_CONTEXT | jq ".event.label"
        echo HHHHHHHHHHHHHHHHHHHHHHHHHHH1
        lables_json=$(echo $GITHUB_CONTEXT | jq ".labels")
        for (( i=0; i<$lables_count; i++ ))
        do
          echo The ${i}th lable: $(echo lables_json | jq ".[$i]")
        done
        echo The PR is merged.
