name: CherryPick
on:
  pull_request_target:
    types:
    - closed
    branches:
    - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        Array = ${{ github.event.pull_request.labels }}
        echo "${Array[*]}"
        echo The PR is merged.
