# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request_target:
    types:
    - opened
    - reopened
    branches:
    - '202012'
    paths:
    - 'files/build/versions/**'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: approve
      run: |
        set -e
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        url=$(echo $GITHUB_CONTEXT | jq -r '.event.pull_request._links.html.href')
        echo PR: $url
        gh pr review $url --approve
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
