name: MSConflictDetect
on:
  pull_request_target:
    branches:
      - 'master'
      - '202[0-9][0-9][0-9]'

jobs:
  MSConflictDetect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Debug
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        USER: mssonicbld
        PAT: ${{ secrets.GH_PAT }}
        TOKEN: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
      run: |
        set -e
        echo $GITHUB_CONTEXT | jq
        git config --global user.email "sonicbld@microsoft.com"
        git config --global user.name "Sonic Build Admin"
        git remote add ms https://$TOKEN@dev.azure.com/msazure/One/_git/Networking-acs-buildimage
        git fetch ms 2>/dev/null

        echo ${PAT} | gh auth login --with-token

        cd ..
        git clone https://$USER:$PAT@github.com/Azure/sonic-pipelines-internal
        cd sonic-pipelines-internal
        git checkout test
        cp azure-pipelines/azdevops_git_api.sh ../
    - name: Main
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
      run: |
        set -e
        branch_base=$(echo $GITHUB_CONTEXT | jq -r ".base_ref")
        pr_id=$(echo $GITHUB_CONTEXT | jq -r ".event.number")

        echo PRID: $pr_id
        export PAT=$AZURE_DEVOPS_EXT_PAT
        . ../azdevops_git_api.sh

        # check conflict
        [[ $branch_base =~ ^202[0-9]{3}$ ]] && branch_int=internal-$branch_base
        [[ $branch_base == master ]] && branch_int=internal
        [[ -z "$branch_int" ]] && echo "bypass branch: $branch_base" && exit 0

        git branch -D test &>/dev/null || true
        git checkout -b test
        git branch -D $branch_int &>/dev/null || true
        git checkout -b $branch_int --track ms/$branch_int

        git merge test && echo "No merge conflicts." && exit 0

        listPR sonicbld/conflict_prefix/$pr_id-fix sonicbld/conflict_prefix/$pr_id-base | jq | tee tmp

        if [[ $(cat tmp | jq .count) != 1 ]];then
          echo "No conflict resolve PR found. from: sonicbld/conflict_prefix/$pr_id-fix. to: sonicbld/conflict_prefix/$pr_id-base"
          conflict_commit=$(git log $branch_int..HEAD --merge --format=%H)
          git merge $conflict_commit~
          git push origin $branch_int:sonicbld/conflict_prefix/$pr_id-base

          git merge $conflict_commit
          git add .
          GIT_EDITOR=/bin/true git merge --continue

          git push ms HEAD:sonicbld/conflict_prefix/$pr_id-fix
          createPR sonicbld/conflict_prefix/$pr_id-fix sonicbld/conflict_prefix/$pr_id-base
          exit 1
        fi

        ts_fix=$(git log ms/sonicbld/conflict_prefix/$pr_id-fix --format=%at -n 1)
        ts_pr=$(git log test --format=%at -n 1)
        [[ $ts_fix < $ts_pr ]] && echo "PR updated, but conflict resolving PR not updated." && exit 1
        [[ $(cat tmp | jq -r .value[0].status) != "completed" ]] && echo "conflict resolving PR not completed." && cat tmp | jq && exit 1

